config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  #get 'top' => 'homes#top'
  patch 'books/:id' => 'books#update', as: 'update_book'
  resources :books

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
  @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = 'Book was successfully created'
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
  end


  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'Book was successfully updated'
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
    flash[:notice] = 'Book was successfully destroy'
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h5><%= flash[:notice] %></h5>

<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>can't be blank error!
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book,url: update_book_path(@book.id),method: :patch do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>

<%= f.submit 'Update Book' %>

<%= link_to "Show",book_path(@book.id) %>
<a href="/books">Back</a>

<% end %>

app/views/books/index.html.erb
<body>
  <h5><%= flash[:notice] %></h5>
  <h2>Books</h2>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
      </tr>
    </thead>

    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><span><%= link_to "Show",book_path(book.id) %></span></td>
        <td><span><%= link_to "Edit",edit_book_path(book.id) %></span></td>
        <td><span><%= link_to "Destroy",book_path(book.id), method: :delete,"data-confirm" => "Are you sure?" %></span></td>
      </tr>
      <% end %>
    </tbody>
  </table>

<h2>New Book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>can't be blank error
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: '/books', method: :post do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>

<% end %>

app/views/books/show.html.erb
<h5><%= flash[:notice] %></h5>

<h4>Title</h4>
  <p><%= @book.title %></p>

<h4>Body</h4>
  <p><%= @book.body %></p>

<%= link_to "Edit",edit_book_path(@book.id) %>
<a href="/books">Back</a>

app/views/homes/top.html.erb
<h1>ようこそ Bookersへ！</h1>
 <p>Bookersでは、さまざまな書類に関するあなたの意見や</p>
 <p>印象を共有し交換することができます</p>
   
 <p><a href="/books">start</a></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>